services:
  # Frontend service
  - type: web
    name: zodiac-web
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: VITE_SUPABASE_URL
        value: https://ybmwyhyylqhkfgtspllm.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZi6InlibXd5aHl5bHFoa2ZndHNwbGxtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTYxOTEyMSwiZXhwIjoyMDU3MTk1MTIxfQ.tkf5T8Bm42GjuUswOPEPFijN1VPTpN7sCCu66dn2Gfs

  # Backend service  
  - type: web
    name: zodiac-api
    env: python
    buildCommand: pip install -r api/requirements.txt
    startCommand: gunicorn --chdir api server:app
    envVars:
      - key: REDIS_HOST
        value: redis-18791.c264.ap-south-1-1.ec2.redns.redis-cloud.com
      - key: REDIS_PORT
        value: 18791
      - key: BOT_TOKEN
        value: 7693246799:AAF30PjRnkpRDowNL58IDrRdW7ALs2VLTGA
      - key: SUPABASE_URL
        value: https://ybmwyhyylqhkfgtspllm.supabase.co
      - key: SUPABASE_SERVICE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZi6InlibXd5aHl5bHFoa2ZndHNwbGxtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTYxOTEyMSwiZXhwIjoyMDU3MTk1MTIxfQ.tkf5T8Bm42GjuUswOPEPFijN1VPTpN7sCCu66dn2Gfs
