services:
  - type: web
    name: wormgpt
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 10000
