services:
  # Frontend static site
  - type: static
    name: wormgpt-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://wormgpt-api.onrender.com

  # Backend API
  - type: web
    name: wormgpt-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn api.server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: USER_DATA_FILE
        value: /data/user_data.json
      - key: CORS_ORIGINS
        value: https://wormgpt-frontend.onrender.com

  # Telegram Bot Service
  - type: web
    name: wormgpt-keygen
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r keygen_requirements.txt
    startCommand: python KEYGEN.PY
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: BOT_TOKEN
        value: "7787758054:AAH1va0pP1USZ10HlTofCQSTkn33k2h68Mw"
      - key: CHANNEL_USERNAME
        value: "hecabruss"
      - key: CHANNEL_LINK
        value: "https://t.me/hecabruss"
      - key: USER_DATA_FILE
        value: /data/user_data.json
