services:
  - type: web
    name: wormgpt
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 18
